import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import Header from "@/components/Header";
import { TransitionProvider } from "@/components/PageTransition";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HR.DEV - Développeur",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className={`${inter.variable}`}>
        <TransitionProvider>
          <Header />
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
