import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.scss";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { TransitionProvider } from "@/components/layout/PageTransition";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HR.DEV - Développeur",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      {/* eslint-disable-next-line @next/next/no-sync-scripts */}
      <script
        src="https://mcp.figma.com/mcp/html-to-design/capture.js"
        async
      ></script>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className={`${inter.variable} ${jetbrainsMono.variable}`}>
        <TransitionProvider>
          <Header />
          {children}
          <Footer />
        </TransitionProvider>
      </body>
    </html>
  );
}
